import ExcelJS from "exceljs";

export const CURRENT_SCHOOL_V8_MATRIX: Record<
  string,
  Array<[string, string, string | number]>
> = {
  "6.A": [
    ["Čj", "Novotná", "5+1"],
    ["M", "Pilat", "4+1"],
    ["Aj", "Syrůčková/Rus", 4],
    ["D", "Kvapilová", 2],
    ["Př", "Šindelářová", 2],
    ["Ov", "Novotná", 1],
    ["Z", "Wild", 2],
    ["Hv", "Moravcová", 1],
    ["Inf", "Vašáková/Kadleček", 1],
    ["F", "Dostálová", 2],
    ["Tv", "Rašková/Šobotník", 2],
    ["Vv", "Pilat", 2],
    ["Pč", "Pilat/Moravcová", 1],
  ],
  "6.B": [
    ["Čj", "Kvapilová", "4+1"],
    ["M", "Dostálová", "4+1"],
    ["Aj", "Prsteková/Hanková", 3],
    ["D", "Kvapilová", 2],
    ["Př", "Šindelářová", 2],
    ["Ov", "Slončíková", 1],
    ["Z", "Slončíková", 2],
    ["Hv", "Moravcová", 1],
    ["Inf", "Vašáková/Kadleček", 1],
    ["F", "Dostálová", 2],
    ["Tv", "Lišková/Vodička/Šobotník", 5],
    ["Vv", "Pilat", 2],
    ["Pč", "Pilat", 1],
  ],
  "6.C": [
    ["Čj", "Novotná", "5+1"],
    ["M", "Šubrtová", "4+1"],
    ["Aj", "Robová/Rus", 4],
    ["D", "Jislová", 2],
    ["Př", "Šindelářová", 2],
    ["Ov", "Novotná", 1],
    ["Z", "Slončíková", 2],
    ["Hv", "Moravcová", 1],
    ["Inf", "Vašáková/Kadleček", 1],
    ["F", "Jakoubková", 2],
    ["Tv", "Mašek/Šárová", 2],
    ["Vv", "Robová", 2],
    ["Pč", "Robová/Pilat", 1],
  ],
  "6.D": [
    ["Čj", "Kvapilová", "4+1"],
    ["M", "Dostálová", "4+1"],
    ["Aj", "Prsteková/Hanková", 3],
    ["D", "Kvapilová", 2],
    ["Př", "Černá", 2],
    ["Ov", "Novotná", 1],
    ["Z", "Slončíková", 2],
    ["Hv", "Moravcová", 1],
    ["Inf", "Vašáková/Kadleček", 1],
    ["F", "Dostálová", 2],
    ["Tv", "Rašková/Mašek", 5],
    ["Vv", "Pilat", 2],
    ["Pč", "Pilat/Moravcová", 1],
  ],
  "7.A": [
    ["Čj", "Jislová", "4+1"],
    ["M", "Dostálová", "5+1"],
    ["Aj", "Prsteková/Syrůčková", 3],
    ["D", "Jislová", 2],
    ["Př", "Šindelářová", 2],
    ["Ov", "Novotná", 1],
    ["Z", "Slončíková", 2],
    ["Hv", "Moravcová", 1],
    ["Inf", "Vašáková/Kadleček", 1],
    ["F", "Schoberová", 2],
    ["Tv", "Šárová/Mašek", 2],
    ["Vv", "Pilat", 2],
    ["Pč", "Pilat/Moravcová", 1],
    ["PkČj", "Kvapilová", 1],
    ["Přpk", "Šindelářová", 1],
    ["Vkz", "Indráková", 1],
  ],
  "7.B": [
    ["Čj", "Jislová", "4+1"],
    ["M", "Zindulková", "4+1"],
    ["Aj", "Vodička/Robová", 3],
    ["D", "Jislová", 2],
    ["Př", "Šindelářová", 2],
    ["Ov", "Šárová", 1],
    ["Z", "Slončíková", 2],
    ["Hv", "Moravcová", 1],
    ["Inf", "Vašáková/Kadleček", 1],
    ["F", "Jakoubková", 2],
    ["Tv", "Lišková/Mašek", 5],
    ["Vv", "Černá", 2],
    ["Pč", "Moravcová/Pilat", 1],
  ],
  "7.C": [
    ["Čj", "Novotná", "4+1"],
    ["M", "Zindulková", "5+1"],
    ["Aj", "Prsteková/Syrůčková", 3],
    ["D", "Vosyková", 2],
    ["Př", "Šindelářová", 2],
    ["Ov", "Syrůčková", 1],
    ["Z", "Slončíková", 2],
    ["Hv", "Moravcová", 1],
    ["Inf", "Vašáková/Kadleček", 1],
    ["F", "Schoberová", 2],
    ["Tv", "Šobotník/Rašková", 2],
    ["Vv", "Pilat", 2],
    ["Pč", "Syrůčková/Moravcová", 1],
    ["PkČj", "Novotná", 1],
    ["Přpk", "Šindelářová", 1],
    ["Vkz", "Přikrylová", 1],
  ],
  "8.A": [
    ["Čj", "Vavřincová", "4+1"],
    ["M", "Schoberová", "4+1"],
    ["Aj", "Prsteková/Syrůčková/Černá", 3],
    ["D", "Vosyková", 2],
    ["Př", "Šindelářová", 2],
    ["Ov", "Vodička", 1],
    ["Z", "Slončíková", 2],
    ["Hv", "Moravcová", 1],
    ["Inf", "Vašáková/Kadleček", 1],
    ["F", "Schoberová", 2],
    ["Tv", "Mašek/Šobotník", 2],
    ["Vv", "Přikrylová", 1],
    ["Pč", "Schoberová/Moravcová", 1],
    ["Chemie", "Šubrtová", 2],
    ["Německý jazyk", "Přikrylová", 3],
    ["Španělský jazyk", "Špánková", 3],
    ["Svs", "Šárová", 1],
    ["Vkz", "Šárová", 1],
  ],
  "8.B": [
    ["Čj", "Vavřincová", "5+1"],
    ["M", "Zindulková", "4+1"],
    ["Aj", "Vodička/Rus", 3],
    ["D", "Vosyková", 2],
    ["Př", "Šindelářová", 1],
    ["Ov", "Vodička", 1],
    ["Z", "Wild", 1],
    ["Hv", "Moravcová", 1],
    ["Inf", "Kadleček", 1],
    ["F", "Schoberová", 2],
    ["Tv", "Vodička/Rašková", 5],
    ["Vv", "Robová", 1],
    ["Pč", "Lišková", 1],
    ["Chemie", "Šubrtová", 2],
    ["Španělský jazyk", "Špánková", 3],
  ],
  "8.C": [
    ["Čj", "Vavřincová", "4+1"],
    ["M", "Jakoubková", "4+1"],
    ["Aj", "Prsteková/Rus/Černá", 3],
    ["D", "Pokorná", 2],
    ["Př", "Šindelářová", 2],
    ["Ov", "Černá", 1],
    ["Z", "Slončíková", 2],
    ["Hv", "Moravcová", 1],
    ["Inf", "Vašáková/Kadleček", 1],
    ["F", "Schoberová", 2],
    ["Tv", "Šobotník/Šárová", 2],
    ["Vv", "Jakoubková", 1],
    ["Pč", "Moravcová/Pilat", 1],
    ["Chemie", "Šubrtová", 2],
    ["Německý jazyk", "Přikrylová", 3],
    ["Španělský jazyk", "Śpánková", 3],
    ["Svs", "Černá", 1],
    ["Vkz", "Přikrylová", 1],
  ],
  "9.A": [
    ["Čj", "Kvapilová", "4+1"],
    ["M", "Jakoubková", "4+1"],
    ["Aj", "Prsteková/Rus/Robová", 4],
    ["D", "Vosyková", 2],
    ["Př", "Šindelářová", 1],
    ["Ov", "Jakoubková", 1],
    ["Z", "Slončíková", 2],
    ["Inf", "Vašáková/Kadleček", 1],
    ["F", "Schoberová", 2],
    ["Tv", "Mašek/Rašková", 2],
    ["Vv", "Jakoubková", 1],
    ["Chemie", "Šubrtová", 2],
    ["Německý jazyk", "Přikrylová", 3],
    ["Svs", "Jakoubková", 1],
  ],
  "9.B": [
    ["Čj", "Pokorná", "4+1"],
    ["M", "Zindulková", "5+1"],
    ["Aj", "Vodička/Syrůčková/Robová", 3],
    ["D", "Pokorná", 2],
    ["Př", "Šindelářová", 1],
    ["Ov", "Vodička", 1],
    ["Z", "Slončíková", 1],
    ["Inf", "Vašáková/Kadleček", 1],
    ["F", "Schoberová", 2],
    ["Tv", "Mašek/Lišková", 4],
    ["Vv", "Šárová", 1],
    ["Chemie", "Šubrtová", 2],
    ["Německý jazyk", "Špánková/Přikrylová", 3],
    ["Svs", "Šárová", 1],
  ],
  "9.C": [
    ["Čj", "Pokorná", "4+1"],
    ["M", "Šubrtová", "4+1"],
    ["Aj", "Robová/Rus/Syrůčková", 4],
    ["D", "Vosyková", 2],
    ["Př", "Šindelářová", 1],
    ["Ov", "Šárová", 1],
    ["Z", "Slončíková", 2],
    ["Inf", "Vašáková/Kadleček", 1],
    ["F", "Schoberová", 2],
    ["Tv", "Šobotník/Šárová", 2],
    ["Vv", "Přikrylová", 1],
    ["Chemie", "Šubrtová", 2],
    ["Německý jazyk", "Přikrylová", 3],
    ["Svs", "Šárová", 1],
  ],
};

export const CURRENT_SCHOOL_V8_LAYOUT: Record<
  string,
  { row: number; column: number }
> = {
  "6.A": { row: 3, column: 2 },
  "6.B": { row: 3, column: 6 },
  "6.C": { row: 3, column: 10 },
  "6.D": { row: 3, column: 14 },
  "7.A": { row: 19, column: 2 },
  "7.B": { row: 19, column: 6 },
  "7.C": { row: 19, column: 10 },
  "8.A": { row: 38, column: 2 },
  "8.B": { row: 38, column: 6 },
  "8.C": { row: 38, column: 10 },
  "9.A": { row: 60, column: 2 },
  "9.B": { row: 60, column: 6 },
  "9.C": { row: 60, column: 10 },
};

export async function currentSchoolV8WorkbookBytes(): Promise<Uint8Array> {
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet("List 1");

  for (const [classCode, position] of Object.entries(
    CURRENT_SCHOOL_V8_LAYOUT,
  )) {
    const rows = CURRENT_SCHOOL_V8_MATRIX[classCode] ?? [];
    sheet.getCell(position.row, position.column).value = classCode;
    sheet.getCell(position.row + 1, position.column).value = "Předměty";
    sheet.getCell(position.row + 1, position.column + 1).value =
      "Učitel/učitelka";
    sheet.getCell(position.row + 1, position.column + 2).value =
      "Časová dotace";
    rows.forEach(([subject, teacher, periods], index) => {
      sheet.getCell(position.row + 2 + index, position.column).value = subject;
      sheet.getCell(position.row + 2 + index, position.column + 1).value =
        teacher;
      sheet.getCell(position.row + 2 + index, position.column + 2).value =
        periods;
    });
  }

  return new Uint8Array(await workbook.xlsx.writeBuffer());
}
